### ISSUE TITLE
dcm2bids error number of volumes

### ISSUE THREAD

**Issue by perronea** [DCAN-Labs/abcd-dicom2bids#47]
Error: Check sorted order: 4D dataset has 1 volumes, but volume index ranges from 1..411
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
Error: Converted 169885 of 194545 files
Traceback (most recent call last):
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 120, in run
    dcm2niix.run(self.forceDcm2niix)
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 90, in run
    self.execute()
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/site-packages/dcm2bids/utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

**Comment by rosemccollum** [comment]
We have determined that this is an issue due to missing DICOMS, please check to see if your DICOM sequence is complete and reopen this issue if you believe that not to be the issue
