### ISSUE TITLE
Update SciPy Version in `src/requirements.txt`

### ISSUE THREAD

**Issue by MIZwally** [DCAN-Labs/abcd-dicom2bids#67]
### What happened?

When running the recommended command `pip install -r src/requirements.txt` encountered an error with installing SciPy version 1.4.1. I tried again after updating the version in `requirements.txt` to 1.5.0, but I still received the same error. The download was successful after updating the version to 1.6.0. 

### What command did you use?

```shell
`pip install -r src/requirements.txt`
```

### What version of abcd-dicom2bids are you using?

Current

### Relevant log output

```shell
Collecting scipy==1.4.1
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [247 lines of output]
      <string>:418: UserWarning: Unrecognized setuptools command ('dist_info --output-dir /tmp/pip-modern-metadata-tgiwt1vc --keep-egg-info'), proceeding with generating Cython sources and expanding templates
      Running from scipy source directory.
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/home/'username'/env/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_lapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/home/'username'/env/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_clapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas,lapack not found in ['/home/'username'/env/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      flame_info:
      customize UnixCCompiler
        libraries flame not found in ['/home/'username'/env/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /home/'username'/env/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/local/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib64/atlas
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib64
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib/sse2
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      lapack_info:
      customize UnixCCompiler
        libraries lapack not found in ['/home/'username'/env/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      /tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      lapack_src_info:
        NOT AVAILABLE

      /tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
        NOT AVAILABLE

      Traceback (most recent call last):
        File "/home/'username'/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/'username'/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/'username'/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 540, in <module>
        File "<string>", line 536, in setup_package
        File "/tmp/pip-build-env-0438r67z/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "<string>", line 435, in configuration
      numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Add any additional information or context about the problem here.

I replaced my username in any /home/* path with 'username'.

**Comment by rosemccollum** [comment]
We have updated the requirements.txt, thank you for pointing this out to us!
